### ISSUE TITLE
Minecraft 1.19.2 not launching

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#106]
I have Java 17 installed and I'm using a cracked version of MultiMC as the launcher
Using VMware Workstation with Windows XP 32-bit

```
[05:05:53] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[05:05:53] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[05:05:53] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:66)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2359)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at efu.a(SourceFile:2354)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:214)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:51)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[05:05:53] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[05:05:53] [Render thread/INFO]: [STDOUT]: Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

```

[Full log](https://paste.ee/p/nXr4q)

**Comment by Skulltrail192** [comment]
And Minicraft run in other system on Vmware?

**Comment by Smu1zel** [comment]
Yeah, I looked at the log and it seems Blaze3D is crashing. This is likely due to VMware drivers not supporting OpenGL 3.2 on XP, which is a requirement since 1.17.

I used the legacy TLauncher, and a software OpenGL renderer and 1.19.2 was able to load up just fine. Though my 768 heap size is probably why I can't get into a world. Or it could be a separate One-Core issue, can't test without a real OpenGL 3.2 system that supports XP.

So it's likely that in this case, this isn't a One-Core-API issue, rather a VMware driver limitation. I'll also note that the issue where Minecraft had no sound has seemingly been fixed in 2.10.

**Comment by Skulltrail192** [comment]
Yes, OpenGL 4.5+ is only support on real hardware. Vmware is limited ad VirtualBox doesn't have accelaration anymore, in any Windows System.

**Comment by Legendary-Candice-Joe** [comment]
On minecraft 1.18.2, even with lan, it seems to not connect to other servers. And worlds just freeze when loading

**Comment by Smu1zel** [comment]
> On minecraft 1.18.2, even with lan, it seems to not connect to other servers. And worlds just freeze when loading

Did you modify Java in any way (like using a software renderer)? Test 1.16.5 and 1.18pre1 unmodified and report back, if worlds work there, then it must be a fault of Java 17 on One-Core-API. 1.16.5 was the last to use Java 8, and 1.18pre1 was the last to use Java 16.

**Comment by Legendary-Candice-Joe** [comment]
I actually did kinda have to modify-ish java.

Because it requires openGL 3.2 (and my drivers are obv too old for that). The only solution I found online was using the mesa3D opengl_32.dll file and put that in the same directory. That doesn't seem to be the issue though. I also tried deleting all of the API-SET dlls in the same directory because one-core-api has its own api-set, but that didn't help either?

And yes, using older versions (all 1.17 versions and lower) function correctly. I don't really need anything higher than 1.18.2 though.

**Comment by Skulltrail192** [comment]
Try again with version 4.0.0.
