### ISSUE TITLE
frpc crashed

### ISSUE THREAD

**Issue by zutyhcx** [Skulltrail192/One-Core-API-Binaries#152]
https://github.com/fatedier/frp

frps(running at windows server 2016):
2023/02/11 23:13:31 [I] [service.go:146] frps tcp listen on 0.0.0.0:7000
2023/02/11 23:13:31 [I] [root.go:204] Start frps success
2023/02/11 23:13:40 [I] [service.go:356] client login info: ip [*****:1128] version [0.28.2] hostname [] os [windows] arch [386]
2023/02/11 23:13:41 [I] [tcp.go:66] [11bc8d0b659b452d] [dispatch] tcp proxy listen port [30443]
2023/02/11 23:13:41 [I] [control.go:398] [11bc8d0b659b452d] new proxy [dispatch] success
2023/02/11 23:13:41 [I] [udp.go:81] [11bc8d0b659b452d] [game] udp proxy listen port [33103]
2023/02/11 23:13:41 [I] [control.go:398] [11bc8d0b659b452d] new proxy [game] success
2023/02/11 23:13:41 [I] [proxy.go:84] [11bc8d0b659b452d] [game] get a new work connection: [*****:1128]
2023/02/11 23:14:06 [I] [proxy.go:84] [11bc8d0b659b452d] [dispatch] get a new work connection: [*****:1128]
2023/02/11 23:14:06 [I] [proxy.go:84] [11bc8d0b659b452d] [dispatch] get a new work connection: [*****:1128]
2023/02/11 23:14:37 [W] [udp.go:99] [11bc8d0b659b452d] [game] read from workConn for udp error: EOF
2023/02/11 23:14:37 [I] [proxy.go:84] [11bc8d0b659b452d] [game] get a new work connection: [*****:1128]
2023/02/11 23:14:37 [I] [control.go:274] [11bc8d0b659b452d] control writer is closing
2023/02/11 23:14:37 [I] [udp.go:153] [11bc8d0b659b452d] [game] sender goroutine for udp work connection closed
2023/02/11 23:14:37 [W] [proxy.go:112] [game] failed to send message to work connection from pool: stream closed, times: 0
2023/02/11 23:14:37 [I] [proxy.go:69] [11bc8d0b659b452d] [dispatch] proxy closing
2023/02/11 23:14:37 [W] [proxy.go:81] [11bc8d0b659b452d] [game] failed to get work connection: control is closed
2023/02/11 23:14:37 [I] [proxy.go:137] [11bc8d0b659b452d] [dispatch] listener is closed
2023/02/11 23:14:37 [I] [proxy.go:69] [11bc8d0b659b452d] [game] proxy closing
2023/02/11 23:14:37 [I] [control.go:350] [11bc8d0b659b452d] client exit success

frpc(running on windows xp sp3):

        /home/wcl/.gvm/gos/go1.12.7/src/runtime/time.go:105 +0x15b
github.com/fatedier/frp/client.(*VisitorManager).Run(0x234b1520)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/visitor_manager
.go:47 +0x14d
created by github.com/fatedier/frp/client.(*Control).Run
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:106
+0x6a

goroutine 18 [chan receive]:
github.com/fatedier/frp/client.(*Service).keepControllerWorking(0x234b4190)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/service.go:121
+0x1c5
created by github.com/fatedier/frp/client.(*Service).Run
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/service.go:102
+0x188

goroutine 19 [select]:
github.com/fatedier/frp/client.(*Control).msgHandler(0x2343b180)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:257
+0x1d3
created by github.com/fatedier/frp/client.(*Control).worker
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:289
+0x37

goroutine 20 [select]:
github.com/fatedier/frp/vendor/github.com/hashicorp/yamux.(*Stream).Read(0x2343b
030, 0x23702858, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/hash
icorp/yamux/stream.go:133 +0x261
crypto/cipher.StreamReader.Read(0x9950a0, 0x23466720, 0x20650b0, 0x234048e0, 0x2
3702858, 0x1, 0x1, 0x42b4d3, 0x43a5ef, 0x1)
        /home/wcl/.gvm/gos/go1.12.7/src/crypto/cipher/io.go:20 +0x41
github.com/fatedier/frp/vendor/github.com/fatedier/golib/crypto.(*Reader).Read(0
x234666f0, 0x23702858, 0x1, 0x1, 0x234370c0, 0x23437440, 0x23433fdc)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/crypto/decode.go:70 +0x6c
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).read
Msg(0x23404260, 0x995300, 0x234666f0, 0x44a550, 0x234370c0, 0x4040d4, 0x234370c0
, 0x23433fdc, 0xccc101)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:32 +0x63
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).Read
Msg(0x23404260, 0x995300, 0x234666f0, 0x7adb80, 0xccc188, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:68 +0x35
github.com/fatedier/frp/models/msg.ReadMsg(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/msg/ctl.go:37
github.com/fatedier/frp/client.(*Control).reader(0x2343b180)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:202
+0x20e
created by github.com/fatedier/frp/client.(*Control).worker
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:290
+0x55

goroutine 21 [chan receive]:
github.com/fatedier/frp/client.(*Control).writer(0x2343b180)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:227
+0x1ac
created by github.com/fatedier/frp/client.(*Control).worker
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:291
+0x73

goroutine 24 [chan receive]:
github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn.func2(0x2065188, 0x2
3404bd0, 0x234376c0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
452 +0x66
created by github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
478 +0x253

goroutine 25 [select]:
github.com/fatedier/frp/vendor/github.com/hashicorp/yamux.(*Stream).Read(0x2343b
340, 0x237023b9, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/hash
icorp/yamux/stream.go:133 +0x261
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).read
Msg(0x23404260, 0x20650b0, 0x23404bd0, 0x23406d88, 0x99ec00, 0x7f2020, 0x407c69,
 0x7ec700, 0x839dc0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:32 +0x63
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).Read
MsgInto(0x23404260, 0x20650b0, 0x23404bd0, 0x7adc40, 0x23404d20, 0x20650c8, 0x23
404bd0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:76 +0x35
github.com/fatedier/frp/models/msg.ReadMsgInto(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/msg/ctl.go:41
github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn.func1(0x2065188, 0x2
3404bd0, 0x23437680)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
434 +0x85
created by github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
479 +0x2a2

goroutine 26 [sleep]:
runtime.goparkunlock(...)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/proc.go:307
time.Sleep(0xfc23ac00, 0x6)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/time.go:105 +0x15b
github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn.func3(0x2065188, 0x2
3404bd0, 0x234376c0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
468 +0x34
created by github.com/fatedier/frp/client/proxy.(*UdpProxy).InWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
480 +0x2f1

goroutine 27 [chan receive]:
github.com/fatedier/frp/models/proto/udp.Forwarder.func2(0x23437680, 0x236f6cc0,
 0x234b1b40, 0x234b1aa0, 0x23404d10)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/proto/udp/udp.g
o:110 +0x35
created by github.com/fatedier/frp/models/proto/udp.Forwarder
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/proto/udp/udp.g
o:109 +0xa6

goroutine 30 [semacquire]:
sync.runtime_Semacquire(0x237025c8)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0x237025c0)
        /home/wcl/.gvm/gos/go1.12.7/src/sync/waitgroup.go:130 +0x7d
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join(0x20651b8, 0x23
404da0, 0x2065090, 0x23404d30, 0x23404da0, 0x4, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:41 +0x122
github.com/fatedier/frp/client/proxy.HandleTcpWorkConnection(0x2343af0c, 0x0, 0x
0, 0x2343aee0, 0x99e4c0, 0x23404d30, 0x23702490, 0x3, 0x8, 0x234b1c20)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
560 +0x907
github.com/fatedier/frp/client/proxy.(*TcpProxy).InWorkConn(0x23404ab0, 0x99e4c0
, 0x23404d30, 0x234b1c20)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
124 +0x8b
created by github.com/fatedier/frp/client/proxy.(*ProxyWrapper).InWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy_wra
pper.go:226 +0x1a2

goroutine 32 [select]:
github.com/fatedier/frp/vendor/github.com/hashicorp/yamux.(*Stream).Read(0x2343b
500, 0x2370260c, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/hash
icorp/yamux/stream.go:133 +0x261
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).read
Msg(0x23404260, 0x20650b0, 0x23404d90, 0x23404d90, 0x23415b00, 0x26, 0x407c69, 0
x7ec700, 0x839dc0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:32 +0x63
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).Read
MsgInto(0x23404260, 0x20650b0, 0x23404d90, 0x7adc00, 0x237180e0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:76 +0x35
github.com/fatedier/frp/models/msg.ReadMsgInto(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/msg/ctl.go:41
github.com/fatedier/frp/client.(*Control).HandleReqWorkConn(0x2343b180, 0xccc188
)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:126
+0x1cb
created by github.com/fatedier/frp/client.(*Control).msgHandler
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:276
+0x345

goroutine 33 [semacquire]:
internal/poll.runtime_Semacquire(0x2349c734)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/sema.go:61 +0x2e
internal/poll.(*FD).Close(0x2349c600, 0x2349c600, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_windows.go:457 +0x69
net.(*netFD).Close(0x2349c600, 0x42918c, 0x20651c8)
        /home/wcl/.gvm/gos/go1.12.7/src/net/fd_windows.go:134 +0x49
net.(*conn).Close(0x23406f40, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/net/net.go:201 +0x3f
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join.func1(0x20651b8
, 0x23404da0, 0x2065090, 0x23404d30, 0x237025b0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:36 +0x189
created by github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:39 +0xda

goroutine 34 [runnable, locked to thread]:
syscall.Syscall(0x7d703f80, 0x2, 0x6c4, 0x2349c614, 0x0, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/syscall_windows.go:184 +0xbb
syscall.CancelIoEx(0x6c4, 0x2349c614, 0x23406108, 0x995201)
        /home/wcl/.gvm/gos/go1.12.7/src/syscall/zsyscall_windows.go:592 +0x5b
internal/poll.(*ioSrv).ExecIO(0xcb9ab8, 0x2349c614, 0x918210, 0xc7ae80, 0x407287
, 0x839dc0)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_windows.go:251 +0x174
internal/poll.(*FD).Read(0x2349c600, 0x2371a000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_windows.go:502 +0x212
net.(*netFD).Read(0x2349c600, 0x2371a000, 0x4000, 0x4000, 0x406ec8, 0xccc134, 0x
7886b6)
        /home/wcl/.gvm/gos/go1.12.7/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x23406f40, 0x2371a000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/net/net.go:177 +0x57
io.copyBuffer(0x20650c8, 0x23404d30, 0x20651d8, 0x23404da0, 0x2371a000, 0x4000,
0x4000, 0x0, 0x0, 0x0, ...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:402 +0xd9
io.CopyBuffer(...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:375
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join.func1(0x2065090
, 0x23404d30, 0x20651b8, 0x23404da0, 0x237025b8)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:35 +0x177
created by github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:40 +0x116

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0x237027e8)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0x237027e0)
        /home/wcl/.gvm/gos/go1.12.7/src/sync/waitgroup.go:130 +0x7d
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join(0x20651b8, 0x23
404e30, 0x2065090, 0x23404dc0, 0x23404e30, 0x4, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:41 +0x122
github.com/fatedier/frp/client/proxy.HandleTcpWorkConnection(0x2343af0c, 0x0, 0x
0, 0x2343aee0, 0x99e4c0, 0x23404dc0, 0x237026b0, 0x3, 0x8, 0x23718160)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
560 +0x907
github.com/fatedier/frp/client/proxy.(*TcpProxy).InWorkConn(0x23404ab0, 0x99e4c0
, 0x23404dc0, 0x23718160)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy.go:
124 +0x8b
created by github.com/fatedier/frp/client/proxy.(*ProxyWrapper).InWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy/proxy_wra
pper.go:226 +0x1a2

goroutine 38 [select]:
github.com/fatedier/frp/vendor/github.com/hashicorp/yamux.(*Stream).Read(0x2343b
5e0, 0x237027ec, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/hash
icorp/yamux/stream.go:133 +0x261
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).read
Msg(0x23404260, 0x20650b0, 0x23404e20, 0x23404e20, 0x23415cc0, 0x26, 0x407c69, 0
x7ec700, 0x839dc0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:32 +0x63
github.com/fatedier/frp/vendor/github.com/fatedier/golib/msg/json.(*MsgCtl).Read
MsgInto(0x23404260, 0x20650b0, 0x23404e20, 0x7adc00, 0x237183a0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/msg/json/process.go:76 +0x35
github.com/fatedier/frp/models/msg.ReadMsgInto(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/msg/ctl.go:41
github.com/fatedier/frp/client.(*Control).HandleReqWorkConn(0x2343b180, 0xccc188
)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:126
+0x1cb
created by github.com/fatedier/frp/client.(*Control).msgHandler
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:276
+0x345

goroutine 39 [select]:
github.com/fatedier/frp/vendor/github.com/hashicorp/yamux.(*Stream).Read(0x2343b
570, 0x2372e000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/hash
icorp/yamux/stream.go:133 +0x261
io.copyBuffer(0x2065220, 0x23404e30, 0x20650b0, 0x23404dc0, 0x2372e000, 0x4000,
0x4000, 0x0, 0x0, 0x0, ...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:402 +0xd9
io.CopyBuffer(...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:375
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join.func1(0x20651b8
, 0x23404e30, 0x2065090, 0x23404dc0, 0x237027d0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:35 +0x177
created by github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:39 +0xda

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x2064f00, 0x72, 0x9969e0)
        /home/wcl/.gvm/gos/go1.12.7/src/runtime/netpoll.go:182 +0x4c
internal/poll.(*pollDesc).wait(0x2349c87c, 0x72, 0xc76100, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_poll_runtime.go:87 +0x7
e
internal/poll.(*ioSrv).ExecIO(0xcb9ab8, 0x2349c794, 0x918210, 0x0, 0x0, 0x4000)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x2349c780, 0x2372a000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/internal/poll/fd_windows.go:502 +0x212
net.(*netFD).Read(0x2349c780, 0x2372a000, 0x4000, 0x4000, 0x406d50, 0x23408000,
0x7ec7c0)
        /home/wcl/.gvm/gos/go1.12.7/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x23406fe8, 0x2372a000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /home/wcl/.gvm/gos/go1.12.7/src/net/net.go:177 +0x57
io.copyBuffer(0x20650c8, 0x23404dc0, 0x20651d8, 0x23404e30, 0x2372a000, 0x4000,
0x4000, 0x0, 0x0, 0x0, ...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:402 +0xd9
io.CopyBuffer(...)
        /home/wcl/.gvm/gos/go1.12.7/src/io/io.go:375
github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join.func1(0x2065090
, 0x23404dc0, 0x20651b8, 0x23404e30, 0x237027d8)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:35 +0x177
created by github.com/fatedier/frp/vendor/github.com/fatedier/golib/io.Join
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fate
dier/golib/io/io.go:40 +0x116

D:\Program Files\soft>

**Comment by tecno14** [comment]
I have also issues with CancelIoEx running RGC app https://www.rankedgaming.com
