### ISSUE TITLE
BakaXL minecraft launcher problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#176]
https://www.bakaxl.com

I try to open this and I get:
[BakaXL-ErrorCan-20230909083752.json.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12564307/BakaXL-ErrorCan-20230909083752.json.txt)

I modified for Windows 7 compatibility and I got
![Windows XP Professional-2023-09-09-08-50-10](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/6163e26a-fa5b-4bf2-9e81-5dc736fd233e)

[56cc_appcompat.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12564318/56cc_appcompat.txt)

**Comment by Skulltrail192** [comment]
Well, append dmp too, please

**Comment by jonm58** [comment]
> Well, append dmp too, please. This app require java?

Application requires .NET Framework 4.8 (I installed it, no Java)
Test system: Windows XP Professional x64 Edition
[dmp](https://drive.google.com/drive/folders/1EuiSIrqm24iXEVM8bklS2P841Z4kmWjK?usp=drive_link)

**Comment by idontyboi** [comment]
[Problem: Win8+ DPI functions always return FALSE [failure]](https://github.com/Skulltrail192/One-Core-Api/blob/c77a4fd6298d0303e35d63db9baef724a8e87b52/wrappers/base/user32_wrapper/main.c#L503) without error being set so it uses the last error of the process thus resulting in a nonsense exception.

To fix this, simply change these two functions to return TRUE, respectively.
Relevant Stack trace:
```
Set property 'BakaXL.UI.Controls.SettingsBigBtn.Icon' threw an exception.
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at MS.Win32.SafeNativeMethods.GetProcessDpiAwareness(HandleRef hProcess)
at MS.Internal.DpiUtil.ProcessDpiAwarenessHelper.GetProcessDpiAwarenessFromWindow(IntPtr hWnd)
at MS.Internal.DpiUtil.ProcessDpiAwarenessHelper.GetProcessDpiAwareness(IntPtr hWnd)
at MS.Internal.DpiUtil.GetProcessDpiAwarenessContextValue(IntPtr hWnd)
at System.Windows.SystemResources.get_ProcessDpiAwarenessContextValue()
at System.Windows.SystemResources.<>c.<EnsureResourceChangeListener>b__23_0(HwndDpiInfo hwndDpiContext)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at System.Windows.SystemResources.EnsureResourceChangeListener()
at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
at System.Windows.FrameworkElement.TryFireInitialized()
at System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
at System.Windows.FrameworkElement.AddLogicalChild(Object child)
at System.Windows.Controls.ContentControl.OnContentChanged(Object oldContent, Object newContent)
at System.Windows.Controls.ContentControl.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
at BakaXL.UI.Controls.SettingsBigBtn.AdOHfI4Rru7TDnBeeAFO(Object , Object )
```

**Comment by jonm58** [comment]
[user.tar.gz](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13533017/user.tar.gz)

3.0.4-20231130-experimental

**Comment by Skulltrail192** [comment]
Try again with version 4.0
