### ISSUE TITLE
ASP.NET Core on Windows xp SP3

### ISSUE THREAD

**Issue by Karimiprogramer** [Skulltrail192/One-Core-API-Binaries#284]
I am a web developer and i am trying to run test ASP.NET Core website on my old computer.at first i am installed ASP.NET Core Runtime binaries x86 on my computer and setting dotnet.exe on PATH variable.when i runnig test website this exception in throwing

C:\Documents and Settings\ASAM\Desktop\publish>dotnet WebApplication1.dll
Process terminated. Encountered infinite recursion while looking up resource 'Ar
gument_CultureNotSupported' in System.Private.CoreLib. Verify the installation o
f .NET is complete and does not need repairing, and that the state of the proces
s has not become corrupted.
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Globalization.CultureInfo.GetCultureNotSupportedExceptionMessage()
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation B
yRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.get_ResourceManager()
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Globalization.CultureInfo.GetCultureNotSupportedExceptionMessage()
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureByName(System.String)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultCulture()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Int32.TryParse(System.ReadOnlySpan`1<Char>, Int32 ByRef)
   at Microsoft.Extensions.Configuration.ConfigurationKeyComparer.<Compare>g__Co
mpare|7_1(System.ReadOnlySpan`1<Char>, System.ReadOnlySpan`1<Char>)
   at Microsoft.Extensions.Configuration.ConfigurationKeyComparer.Compare(System
.String, System.String)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, System.Priva
te.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
SwapIfGreater(System.Span`1<System.__Canon>, System.Comparison`1<System.__Canon>
, Int32, Int32)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, System.Priva
te.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
IntroSort(System.Span`1<System.__Canon>, Int32, System.Comparison`1<System.__Can
on>)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, System.Priva
te.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
IntrospectiveSort(System.Span`1<System.__Canon>, System.Comparison`1<System.__Ca
non>)
   at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, System.Priva
te.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
Sort(System.Span`1<System.__Canon>, System.Comparison`1<System.__Canon>)
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib,
 Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Sort(System
.Comparison`1<System.__Canon>)
   at Microsoft.Extensions.Configuration.ConfigurationProvider.GetChildKeys(Syst
em.Collections.Generic.IEnumerable`1<System.String>, System.String)
   at Microsoft.Extensions.Configuration.InternalConfigurationRootExtensions+<>c
__DisplayClass0_0.<GetChildrenImplementation>b__0(System.Collections.Generic.IEn
umerable`1<System.String>, Microsoft.Extensions.Configuration.IConfigurationProv
ider)
   at System.Linq.Enumerable.Aggregate[[System.__Canon, System.Private.CoreLib,
Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Can
on, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7ce
c85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System
.__Canon, System.Func`3<System.__Canon,System.__Canon,System.__Canon>)
   at Microsoft.Extensions.Configuration.InternalConfigurationRootExtensions.Get
ChildrenImplementation(Microsoft.Extensions.Configuration.IConfigurationRoot, Sy
stem.String)
   at Microsoft.Extensions.Configuration.ConfigurationSection.GetChildren()
   at Microsoft.Extensions.Logging.LoggerFilterConfigureOptions.LoadDefaultConfi
gValues(Microsoft.Extensions.Logging.LoggerFilterOptions)
   at Microsoft.Extensions.Logging.LoggerFilterConfigureOptions.Configure(Micros
oft.Extensions.Logging.LoggerFilterOptions)
   at Microsoft.Extensions.Options.OptionsFactory`1[[System.__Canon, System.Priv
ate.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
.Create(System.String)
   at Microsoft.Extensions.Options.OptionsMonitor`1+<>c[[System.__Canon, System.
Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea779
8e]].<Get>b__10_0(System.String, Microsoft.Extensions.Options.IOptionsFactory`1<
System.__Canon>)
   at Microsoft.Extensions.Options.OptionsCache`1+<>c__DisplayClass3_1`1[[System
.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyTok
en=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, C
ulture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetOrAdd>b__2()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cu
lture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.Laz
yThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cu
lture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.
LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cu
lture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cu
lture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1[[System.__Canon, System.Privat
e.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].G
etOrAdd[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutra
l, PublicKeyToken=7cec85d7bea7798e]](System.String, System.Func`3<System.String,
System.__Canon,System.__Canon>, System.__Canon)
   at Microsoft.Extensions.Options.OptionsMonitor`1[[System.__Canon, System.Priv
ate.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
.Get(System.String)
   at Microsoft.Extensions.Options.OptionsMonitor`1[[System.__Canon, System.Priv
ate.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
.get_CurrentValue()
   at Microsoft.Extensions.Logging.LoggerFactory..ctor(System.Collections.Generi
c.IEnumerable`1<Microsoft.Extensions.Logging.ILoggerProvider>, Microsoft.Extensi
ons.Options.IOptionsMonitor`1<Microsoft.Extensions.Logging.LoggerFilterOptions>,
 Microsoft.Extensions.Options.IOptions`1<Microsoft.Extensions.Logging.LoggerFact
oryOptions>, Microsoft.Extensions.Logging.IExternalScopeProvider)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Sign
ature, Boolean)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(System.O
bject, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Ob
ject, System.Span`1<System.Object>, System.Reflection.BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(System.Object, Syste
m.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Glo
balization.CultureInfo)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingF
lags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInf
o)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.Con
structorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.Runtime
ResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(Micro
soft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Ext
ensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.Servi
ceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolv
erContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(Microsoft
.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensi
ons.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.Con
structorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.Runtime
ResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(Micro
soft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Ext
ensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.Servi
ceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolv
erContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(Microsoft
.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensi
ons.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.Con
structorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.Runtime
ResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(Micro
soft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Ext
ensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.Servi
ceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolv
erContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(Microsoft
.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensi
ons.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.Resolve(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallS
ite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngin
eScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAcce
ssor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions
.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.Depen
dencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae6
0],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, Pu
blicKeyToken=7cec85d7bea7798e]].GetOrAdd(Microsoft.Extensions.DependencyInjectio
n.ServiceLookup.ServiceIdentifier, System.Func`2<Microsoft.Extensions.Dependency
Injection.ServiceLookup.ServiceIdentifier,System.__Canon>)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Micros
oft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Ex
tensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System
.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.
GetRequiredService(System.IServiceProvider, System.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.
GetRequiredService[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cul
ture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.IServiceProvider)
   at Microsoft.Extensions.Hosting.HostBuilder+<>c__DisplayClass35_0.<PopulateSe
rviceCollection>b__2(System.IServiceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(Micro
soft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Ext
ensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.Servi
ceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolv
erContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[
Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, M
icrosoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60],[System.__Canon, System.Private.CoreLib, Version=8.0
.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(Microsoft
.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensi
ons.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso
lver.Resolve(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallS
ite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngin
eScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAcce
ssor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions
.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.Depen
dencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae6
0],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, Pu
blicKeyToken=7cec85d7bea7798e]].GetOrAdd(Microsoft.Extensions.DependencyInjectio
n.ServiceLookup.ServiceIdentifier, System.Func`2<Microsoft.Extensions.Dependency
Injection.ServiceLookup.ServiceIdentifier,System.__Canon>)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Micros
oft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Ex
tensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System
.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.
GetRequiredService(System.IServiceProvider, System.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.
GetRequiredService[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Cul
ture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.IServiceProvider)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(System.IServiceProvid
er, System.Diagnostics.DiagnosticListener)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(System.String[])

**Comment by Skulltrail192** [comment]
Test again with version 4.0.0.

**Comment by Karimiprogramer** [comment]
I have tested a very simple app again and now I have problem with `BCrypt.dll`
```
C:\Documents and Settings\ASAM\Desktop\dotnet>dotnet.exe "C:\Documents and Setti
ngs\ASAM\Desktop\net8.0\WebApplication1.dll"
Unhandled exception. System.TypeInitializationException: The type initializer fo
r 'System.Marvin' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'BCrypt.dll' or one of its
 dependencies: A dynamic link library (DLL) initialization routine failed. (0x80
07045A)
   at Interop.GetRandomBytes(Byte* buffer, Int32 length)
   at System.Marvin..cctor()
   --- End of inner exception stack trace ---
   at System.Collections.Hashtable.InitHash(Object key, Int32 hashsize, UInt32&
seed, UInt32& incr)
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add
)
   at System.Environment.GetEnvironmentVariables()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariabl
esConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigu
rationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensio
ns.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions.AddEnvir
onmentVariables(IConfigurationBuilder configurationBuilder, String prefix)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOpt
ions options, Boolean slim, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateSlimBuilder(String[] arg
s)
   at Program.<Main>$(String[] args) in C:\Users\shahn\source\repos\WebApplicati
on1\Program.cs:line 3
```
