### ISSUE TITLE
Java 17 nio.dll: The specified procedure could not be found

### ISSUE THREAD

**Issue by zutyhcx** [Skulltrail192/One-Core-API-Binaries#97]
I try running a server software reimplementation for a certain anime game by java 17. But something wrong has occured.

https://github.com/Grasscutters/Grasscutter

D:\Program Files\grasscutter>java -jar grasscutter.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\Program Files\jdk-17.0.4.1+1\bin\nio.dll: The specified procedure could not be found
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:270)
        at java.base/jdk.internal.loader.BootLoader.loadLibrary(BootLoader.java:149)
        at java.base/sun.nio.fs.WindowsNativeDispatcher.<clinit>(WindowsNativeDispatcher.java:1171)
        at java.base/sun.nio.fs.WindowsFileAttributes.get(WindowsFileAttributes.java:307)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:51)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:552)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:778)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686)

**Comment by Legendary-Candice-Joe** [comment]
I came across this issue when trying to run minecraft. This procedure seems to be "GetQueuedCompletionStatusEx", I believe this was available in one-core 2.5.0 but using HXD to modify nio.dll to run off of the older ntdll.dll file, it through some other error. I put it in a debugger and it gave an exception. Something like "NT_WRONG_STUB_VERSION".

The creator of one-core-api said that he removed this function from 2.6.0 onward.

All I know is that it's GetQueuedCompletionStatusEx thats missing. But I wish Java gave better errors. Thats all I know, I can't really help beyond that.

**Comment by Smu1zel** [comment]
Swapping nio.dll with the one from Java 16 allows 17 to run in my testing. But hinders software that expects the correct nio, such as Minecraft 1.19.1. Which crashed during world creation for me.

**Comment by Skulltrail192** [comment]
Reenabled GetQueuedCompletionStatusEx function, so, i hope this fixed.
